version: '3'

services:
  service-desk-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      # For development, you can mount these directories to see changes without rebuilding
      # Comment out in production
      - ./schemas:/app/schemas
      - ./agents:/app/agents
      - ./services:/app/services
      - ./main.py:/app/main.py
      - ./agent_server.py:/app/agent_server.py
    restart: unless-stopped
